// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PpvRecon.Infrastructure.Persistence;

#nullable disable

namespace PpvRecon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PpvReconDbContext))]
    [Migration("20260627050941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PpvRecon.Domain.Entities.Auditing.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmailSnapshot")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserRoleSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Module");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableInApp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EventType")
                        .IsUnique();

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JwtId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedIp")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplacedBySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevokedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("RevokedAtUtc");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Jobs.ExternalApiRawResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRunItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("JobRunItemId");

                    b.HasIndex("ParkId");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("Source", "BusinessDate", "ParkId");

                    b.ToTable("ExternalApiRawResponses", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Jobs.JobRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TriggeredByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("JobName", "BusinessDate");

                    b.ToTable("JobRuns", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Jobs.JobRunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RawResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("ParkId");

                    b.HasIndex("RawResponseId");

                    b.HasIndex("ResolvedAtUtc");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("BusinessDate", "ParkId", "Source");

                    b.ToTable("JobRunItems", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Parks.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiProfileId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiSiteId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BalanceTransformRule")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreditLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("PaymentType");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Parks", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Parks.ParkRefund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerRefundAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerRefundStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParkCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParkNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParkRefundAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParkRefundStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketTypeCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketTypeName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerRefundStatus");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParkId");

                    b.HasIndex("ParkRefundStatus");

                    b.HasIndex("PaymentType");

                    b.HasIndex("RefundDate");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ParkRefunds", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Parks.ParkTicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CostPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketGroupName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParkId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("ParkId", "Code");

                    b.HasIndex("ParkId", "TicketTypeCode")
                        .IsUnique();

                    b.ToTable("ParkTicketTypes", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Reconciliation.ParkReconciliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActualBalance")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AdditionalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AdjustmentAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjustmentNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpectedBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastBuiltJobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MissingActualBalance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MissingBankTransaction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MissingPreviousBalance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MissingTicketCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PreviousBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousBusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RebuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedSourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SourceChangedAfterResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UsedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("VarianceAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastBuiltJobRunId");

                    b.HasIndex("ParkId");

                    b.HasIndex("PaymentType");

                    b.HasIndex("ResolvedAtUtc");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("BusinessDate", "ParkId")
                        .IsUnique();

                    b.ToTable("ParkReconciliations", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Settings.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("NotificationType", "Email")
                        .IsUnique();

                    b.ToTable("NotificationRecipients", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Settings.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Jobs.ScheduleTime",
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gio chay job hang ngay theo mui gio Asia/Bangkok.",
                            IsSensitive = false,
                            Value = "23:59",
                            ValueType = "String"
                        },
                        new
                        {
                            Key = "Jobs.ApiTimeoutSeconds",
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Timeout cho tung API call.",
                            IsSensitive = false,
                            Value = "30",
                            ValueType = "Int"
                        },
                        new
                        {
                            Key = "Jobs.ApiRetryCount",
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "So lan retry khi API loi.",
                            IsSensitive = false,
                            Value = "2",
                            ValueType = "Int"
                        },
                        new
                        {
                            Key = "Jobs.ApiRetryDelaySeconds",
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thoi gian cho co dinh giua cac lan retry.",
                            IsSensitive = false,
                            Value = "5",
                            ValueType = "Int"
                        },
                        new
                        {
                            Key = "Audit.RetentionDays",
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "So ngay giu audit log.",
                            IsSensitive = false,
                            Value = "365",
                            ValueType = "Int"
                        },
                        new
                        {
                            Key = "Email.EnableSyncErrorSummary",
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bat gui email tong hop loi dong bo.",
                            IsSensitive = false,
                            Value = "true",
                            ValueType = "Bool"
                        });
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Summaries.DailyBankTransactionSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RawResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceJobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceJobRunItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCreditAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDebitAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParkId");

                    b.HasIndex("PaymentType");

                    b.HasIndex("RawResponseId");

                    b.HasIndex("SourceJobRunId");

                    b.HasIndex("SourceJobRunItemId");

                    b.HasIndex("SourceType");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("BusinessDate", "ParkId", "TransactionType")
                        .IsUnique();

                    b.ToTable("DailyBankTransactionSummaries", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Summaries.DailyParkBalanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AvailableBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankAccountSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentDebt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RawResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceJobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceJobRunItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParkId");

                    b.HasIndex("PaymentType");

                    b.HasIndex("RawResponseId");

                    b.HasIndex("SourceJobRunId");

                    b.HasIndex("SourceJobRunItemId");

                    b.HasIndex("SourceType");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("BusinessDate", "ParkId")
                        .IsUnique();

                    b.ToTable("DailyParkBalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Summaries.DailyTicketCostSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RawResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceJobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceJobRunItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalSalesAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTicketCost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParkId");

                    b.HasIndex("PaymentType");

                    b.HasIndex("RawResponseId");

                    b.HasIndex("SourceJobRunId");

                    b.HasIndex("SourceJobRunItemId");

                    b.HasIndex("SourceType");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("BusinessDate", "ParkId")
                        .IsUnique();

                    b.ToTable("DailyTicketCostSummaries", (string)null);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Auditing.AuditLog", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.NotificationPreference", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.UserPreference", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Identity.UserSession", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.UserSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Jobs.ExternalApiRawResponse", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRun", null)
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRunItem", null)
                        .WithMany()
                        .HasForeignKey("JobRunItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Jobs.JobRun", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Jobs.JobRunItem", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRun", null)
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.ExternalApiRawResponse", null)
                        .WithMany()
                        .HasForeignKey("RawResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Parks.Park", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Parks.ParkRefund", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Parks.ParkTicketType", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Reconciliation.ParkReconciliation", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRun", null)
                        .WithMany()
                        .HasForeignKey("LastBuiltJobRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Settings.NotificationRecipient", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Settings.SystemSetting", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Summaries.DailyBankTransactionSummary", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.ExternalApiRawResponse", null)
                        .WithMany()
                        .HasForeignKey("RawResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRun", null)
                        .WithMany()
                        .HasForeignKey("SourceJobRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRunItem", null)
                        .WithMany()
                        .HasForeignKey("SourceJobRunItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Summaries.DailyParkBalanceSnapshot", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.ExternalApiRawResponse", null)
                        .WithMany()
                        .HasForeignKey("RawResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRun", null)
                        .WithMany()
                        .HasForeignKey("SourceJobRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRunItem", null)
                        .WithMany()
                        .HasForeignKey("SourceJobRunItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PpvRecon.Domain.Entities.Summaries.DailyTicketCostSummary", b =>
                {
                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Parks.Park", null)
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.ExternalApiRawResponse", null)
                        .WithMany()
                        .HasForeignKey("RawResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRun", null)
                        .WithMany()
                        .HasForeignKey("SourceJobRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Jobs.JobRunItem", null)
                        .WithMany()
                        .HasForeignKey("SourceJobRunItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PpvRecon.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
